DIR:
    RADIO_PACKET: 'packet/radio_packet.json'
    RADIO_COMMS:  'sudo ./../private/cpp/radio_comms'
    PI_PACKET:    'packet/pi_packet.json'

F1_SENSORS: 'temp humidity heat'
F1_PINS: '2 3 4 5 6 7 8 9 10'